SolvroTransportAssistant/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.Home.as_view(), name="home"),
    path("user/", include("users.urls")),
    path("stops", views.Stops.as_view(), name="stops"),
    path("api/stops", views.StopsAPI.as_view(), name="stops_api"),
    path(
        "shortest_route", views.ShortestRoute.as_view(), name="shortest_route"
    ),
    path(
        "api/path", views.ShortestRouteAPI.as_view(), name="shortest_route_api"
    ),
    path("favourites", views.Favourites.as_view(), name="favourites"),
    path("map", views.Map.as_view(), name="map"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup", views.SignUp.as_view(), name="signup"),
    path("signin", views.SignIn.as_view(), name="signin"),
    path("signout", views.SignOut.as_view(), name="signout"),
]

main/models.py
from django.db import models
from users.models import CustomUser

# Create your models here.

class Favourite(models.Model):
    source = models.CharField(max_length=255)
    target = models.CharField(max_length=255)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.source + ' - ' + self.target

main/forms.py
from django.forms import ModelForm
from .models import Favourite

class FavouriteForm(ModelForm):
    class Meta:
        model = Favourite
        fields = ['source', 'target']

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from scripts.solvro_city import SolvroCity
from .forms import FavouriteForm
from .models import Favourite
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import views
from rest_framework.response import Response
from .serializers import StopsSerializer, ShortestRouteSerializer
import json
import re


class Home(View):
    def get(self, request):
        return render(request, "main/home.html")


class Stops(View):
    def get(self, request):
        solvro = SolvroCity("scripts")
        return render(
            request, "main/stops.html", {"stops": solvro.get_all_stops()}
        )


class StopsAPI(views.APIView):
    def get(self, request):
        solvro = SolvroCity("scripts")

        data = solvro.get_all_stops()
        result = StopsSerializer(data, many=True).data
        return Response(result)


class ShortestRoute(View):
    template_name = "main/shortest_route_form.html"
    solvro = SolvroCity("scripts")

    def get(self, request):
        # show the form
        return render(
            request,
            self.template_name,
            {"stops": self.solvro.get_all_stops()},
        )

    def post(self, request):
        try:
            # validate source and target provided data
            source = request.POST.get("source")
            target = request.POST.get("target")

            # check if stops exists
            self.solvro.get_stop_id(source)
            self.solvro.get_stop_id(target)

            # return the shortest route with a distance
            return render(
                request,
                "main/shortest_route.html",
                {
                    "shortest_route": self.solvro.get_shortest_route(
                        source, target
                    ),
                    "source": source,
                    "target": target,
                },
            )
        except ValueError:
            return render(
                request,
                self.template_name,
                {"error": "Wrong data provided."},
            )


class ShortestRouteAPI(views.APIView):
    def get(self, request):
        try:
            solvro = SolvroCity("scripts")

            # validate GET parameters
            source = request.GET.get("source")
            target = request.GET.get("target")

            # check if stops exists
            solvro.get_stop_id(source)
            solvro.get_stop_id(target)

            data = solvro.get_shortest_route(source, target)
            result = ShortestRouteSerializer(data).data
            return Response(result)
        except ValueError:
            return Response(
                ShortestRouteSerializer({"distance": 0, "route": []}).data
            )


class Favourites(LoginRequiredMixin, View):
    template_name = "main/favourites.html"

    def get(self, request):
        # show the list
        favourites = Favourite.objects.filter(user=request.user)
        return render(request, self.template_name, {"favourites": favourites})

    def post(self, request):
        try:
            # check if favourite doesn't exist already
            if not Favourite.objects.filter(
                user=request.user,
                source=request.POST.get("source"),
                target=request.POST.get("target"),
            ):
                form = FavouriteForm(request.POST)
                new_favourite = form.save(commit=False)
                new_favourite.user = request.user
                new_favourite.save()
            return redirect("favourites")
        except ValueError:
            return redirect("home")


class Map(View):
    def get(self, request):
        solvro = SolvroCity("scripts")
        return render(
            request,
            "main/map.html",
            {"stops": solvro.get_all_stops(), "links": solvro.get_all_links()},
        )

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A simple application that allows you to find the shortest route between two stops in Solvro City.">
    <meta name="author" content="Paweł Kolman - pawelkolman.github.io">
    
    <title>{% block title %}{% endblock %} - Solvro Transport Assisstant</title>

    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <meta name="theme-color" content="#2e4272"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
  </head>
  
  
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}">Solvro Transport Assistant</a></h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'stops' %}">All stops</a>
        <a class="p-2 text-dark" href="{% url 'shortest_route' %}">Shortest route</a>
      </nav>
      <nav>
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary mr-2" href="{% url 'favourites' %}">{{ user }}</a>
        <form class="d-inline" action="{% url 'users:signout' %}" method="POST">{% csrf_token %}<button type="submit" class="btn btn-primary">Sign out</button></form>
        
        {% else %}
        <a class="btn btn-outline-primary mr-2" href="{% url 'users:signup' %}">Create account</a>
        <a class="btn btn-primary" href="{% url 'users:signin' %}">Sign in</a>
        
        {% endif %}
      </nav>
    </div>

    
    <div class="container content">
      {% block content %}{% endblock %}
    </div>
    
    <footer class="d-flex border-top pt-3">
      <div class="container">
        <div class="row">
          <div class="col-12 col-md mb-3 mb-md-0">
            <a href="https://pawelkolman.github.io" target="_blank">
              <img src="{% static 'img/pk_logo.svg' %}" width="40"/>
            </a>
          </div>
          <div class="col-md">
            <h5>All stops</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="{% url 'stops' %}">See the list</a></li>
              <li><a class="text-muted" href="{% url 'stops_api' %}">API</a></li>
            </ul>
          </div>
          <div class="col-md">
            <h5>Shortest route</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="{% url 'shortest_route' %}">Find it</a></li>
              <li><a class="text-muted" href="{% url 'shortest_route_api' %}">API</a></li>
            </ul>
          </div>
          <div class="col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="https://github.com/pawelkolman/SolvroTransportAssistant" target="_blank">Project</a></li>
              <li><a class="text-muted" href="https://pawelkolman.github.io" target="_blank">Author</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    
  </body>
  
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>

main/templates/main/favourites.html
{% extends 'main/base.html' %}
{% block title %}Favourites{% endblock %}

{% block content %}


{% if favourites %}
  <h1 class="display-4 text-center my-5">Your favourites</h1>
  {% for favourite in favourites %}
    <form method="post" action="{% url 'shortest_route' %}">
      {% csrf_token %}
      <input type="hidden" name="source" value="{{ favourite.source }}">
      <input type="hidden" name="target" value="{{ favourite.target }}">
      <button type="submit" class="btn btn-lg d-block mb-3 mx-auto btn-outline-primary">{{ favourite.source }} - {{ favourite.target }}</button>
    </form>
  {% endfor %}
{% else %}
  <h1 class="display-4 text-center my-5">You don't have any favourites.</h1>
{% endif %}

{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

{% load static %}

<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <img src="{% static 'img/SolvroTransportAssistant_logo.png' %}" width="300"/>
  <h1 class="display-4">Welcome to Solvro Transport Assistant</h1>
  <p class="lead">An amazing application that allows you to find the shortest route between two stops in Solvro City.</p>
</div>

<div class="row">
  <div class="col-md-6">
    <a href="{% url 'shortest_route' %}" class="btn btn-lg btn-block btn-outline-primary mb-3">Find the shortest route</a>
  </div>
  <div class="col-md-6">
    <a href="{% url 'map' %}" class="btn btn-lg btn-block btn-outline-primary mb-3">Show Solvro City map</a>
  </div>
</div>
    
{% endblock %}

main/templates/main/map.html
{% extends 'main/base.html' %}

{% block title %}Map{% endblock %}

{% block content %}

{% load static %}

<style>
   svg {
    width: 100%;
    height: 100%;
  }
  
  #map {
    height: 70vh;
  }
  
  #map rect#background {
    fill: #F4F5F4;
  }
  
  #map circle {
    fill: #2e4272;
    stroke: none;
  }
  
  #map line.selected {
    stroke: #2e4272;
  }
  
  #map polyline {
    stroke: #6583c8;
  }
</style>
<link rel="stylesheet" href="{% static 'map/ggraph.css' %}" />
<script src="{% static 'map/d3.js' %}"></script>
<script src="{% static 'map/marker/marker.js' %}"></script>

<script src="{% static 'map/algorithms/ladjust.js' %}"></script>

<script src="{% static 'map/modules/labels.js' %}"></script>
<script src="{% static 'map/modules/groups.js' %}"></script>
<script src="{% static 'map/modules/nodes.js' %}"></script>
<script src="{% static 'map/modules/selection.js' %}"></script>

<script src="{% static 'map/modules/member_lines.js' %}"></script>


<script src="{% static 'map/ggraph.js' %}"></script>

<h1 class="display-4 text-center my-5">Solvro City map</h1>
<div id="map"></div>


<script>
var all;
var selected;
var graph;
var converted;
var type = null;

ggraph.init('map');

var merge = function() {
  ggraph.merge(selection.all());
}

var remove = function() {
  var s = [];
  for (var k in selected) {
    s.push({id: k})
  }
  ggraph.remove(s);
}

var split = function() {
  ggraph.split(all);
}

function _singles(e) {
  var groups = singles.get_groups(converted);
  all = groups;
  ggraph.merge(groups);
};

function _backbones(e) {
  var res = simmelian.filter(converted.all_links);
  ggraph.filter_links(res);
};

function _set_comment() {
  if (selection.all().length === 0) return;
  var comment = document.getElementById('comment').value;
  var mock = ggraph.convert({
    nodes: [{id: comment, type: 'comment'}],
    links: []
  });

  var original = ggraph.get_graph();
  var comment_obj = mock.nodes[0];

  original.nodes.push(comment_obj);

  for (var key in mock.member_map) {
    original.member_map[key] = mock.member_map[key];
  }

  for (var key in mock.group_map) {
    original.group_map[key] = original.nodes.length - 1;
  }

  document.getElementById('comment').value = '';

  original.all_links[comment] = {}

  var tx = 0;
  var ty = 0;

  selection.all().map(function(selected) {
    var group_id = original.member_map[selected.id].group;
    var target = original.nodes[original.group_map[group_id]];
    tx += target.x;
    ty += target.y;

    original.all_links[comment][selected.id] = 1;
    original.links.push({
      source: comment_obj,
      target: target,
      value: 1
    })
  });

  comment_obj.x = tx / selection.all().length;
  comment_obj.y = ty / selection.all().length;

  ggraph.draw(original);

  selection.clear();
}

ggraph.on_select(function(_all, _selected) {
  all = selection.all();
  selected = selection.selected();
});

var graph = {
  nodes:[
    {% for stop in stops %}
    {id: "{{ stop.name }}"},
    {% endfor %}
  ],
  links: [
    {% for link in links %}
    {source: "{{ link.source }}", target: "{{ link.target }}"},
    {% endfor %}
  ]
}

converted = ggraph.convert(graph);

ggraph.draw(converted);
</script>
    
{% endblock %}

main/templates/main/shortest_route.html
{% extends 'main/base.html' %}
{% block title %}Shortest route{% endblock %}

{% block content %}

{% if shortest_route %}
  <h1 class="display-4 text-center my-5">Shortest route</h1>

  <div class="col-md-6 mx-auto">
    {% for stop in shortest_route.route %}
      <div class="card card-body mb-3">{{ stop.name }}</div>
    {% endfor %}
  </div>

  <h1 class="display-4 text-center my-5">Distance: {{ shortest_route.distance }}</h1>
{% else %}
  <h1 class="display-4 text-center my-5">Unfortunatelly, source and target are not connected.</h1>
{% endif %}

<div class="text-center">
  {% if shortest_route and user.is_authenticated %}
    <form class="d-inline" method="post" action="{% url 'favourites' %}">
      {% csrf_token %}
      <input type="hidden" name="source" value="{{ source }}">
      <input type="hidden" name="target" value="{{ target }}">
      <button type="submit" name="operation" value="add" class="btn btn-outline-primary">Add to favourites</button>
    </form>
  {% endif %}
  <a class="btn btn-primary" href="{% url 'shortest_route' %}">Back</a>
</div>

{% endblock %}

main/templates/main/shortest_route_form.html
{% extends 'main/base.html' %}
{% block title %}Shortest route{% endblock %}

{% block content %}

{% if error %}
<div class="alert alert-primary col-md-6 mx-auto mt-3" role="alert">
  {{ error }}
</div>
{% endif %}

<div class="card card-body col-md-6 mx-auto pt-4">
    <h1 class="display-4 text-center">Find shortest route</h1>
    
    <form method="post">
      {% csrf_token %}
      
      <div class="form-group">
        <label for="id_source">Source</label>
        <select class="form-control" name="source" id="id_source" required>
          <option disabled selected></option>
          {% for stop in stops %}
          <option>{{ stop.name }}</option>
          {% endfor %}
        </select>
      </div>
      
      <div class="form-group">
        <label for="id_target">Target</label>
        <select class="form-control" name="target" id="id_target" required>
          <option disabled selected></option>
          {% for stop in stops %}
          <option>{{ stop.name }}</option>
          {% endfor %}
        </select>
      </div>
      
      <div class="text-center">
        <button type="submit" class="btn btn-primary">Next</button>
      </div>
      
    </form>
  
</div>

{% endblock %}

main/templates/main/stops.html
{% extends 'main/base.html' %}
{% block title %}All stops{% endblock %}

{% block content %}

<h1 class="display-4 text-center my-5">All stops in Solvro City</h1>

<div class="row">
{% for stop in stops %}
  <div class="col-md-6 py-3">
    <div class="card card-body">{{ stop.name }}</div>
  </div>
{% endfor %}
</div>

{% endblock %}